import {
  PERSONAL_COURSES_ROUTE_KEY,
  PERSONAL_COURSES_ROUTE_PATH,
  PERSONAL_COURSES_ROUTE_TITLE,
  PERSONAL_COURSES_ROUTE_URL,
} from "./constants";

export const personalCoursesRouteConfig = {
  key: {
    PERSONAL_COURSES: PERSONAL_COURSES_ROUTE_KEY,
  },
  path: {
    [PERSONAL_COURSES_ROUTE_KEY]: PERSONAL_COURSES_ROUTE_PATH,
  },
  title: {
    [PERSONAL_COURSES_ROUTE_KEY]: PERSONAL_COURSES_ROUTE_TITLE,
  },
  url: {
    [PERSONAL_COURSES_ROUTE_KEY]: PERSONAL_COURSES_ROUTE_URL,
  },
};
