export const datePickerStyles = {
  root: "rounded-md border border-slate-300 bg-slate-800  text-white p-4 w-fit ",
  month: "space-y-4",
  month_caption: "flex items-center",
  caption_label: "text-sm font-semibold",
  button_previous: "mr-2",
  weekdays: "flex",
  weekday: "flex-1 text-center text-xs font-medium uppercase text-slate-200",
  week: "flex",
  day: "h-9 w-9 p-0 ",
  day_button: "size-9 rounded-full text-sm cursor-pointer ",
  today: "font-semibold text-rose-400",
  selected: "bg-blue-600 rounded-full scale-108 transition-all duration-200",
  disabled: "text-slate-400 opacity-50",
  outside: "text-slate-300",
};
