import type { TableRow } from "./types";
export const mockTableData = [
  {
    id: "USR-001",
    name: "Nguyễn Văn An",
    email: "an.nguyen@example.com",
    role: "Admin",
    status: "Active",
    createdAt: "2026-01-15",
    amount: 1250000,
  },
  {
    id: "USR-002",
    name: "Trần Thị Bích",
    email: "bich.tran@example.com",
    role: "Editor",
    status: "Pending",
    createdAt: "2026-02-01",
    amount: 850000,
  },
  {
    id: "USR-003",
    name: "Lê Hoàng Cường",
    email: "cuong.le@example.com",
    role: "User",
    status: "Active",
    createdAt: "2026-02-10",
    amount: 2100000,
  },
  {
    id: "USR-004",
    name: "Phạm Minh Dung",
    email: "dung.pham@example.com",
    role: "User",
    status: "Inactive",
    createdAt: "2026-03-05",
    amount: 0,
  },
  {
    id: "USR-005",
    name: "Vũ Anh Khoa",
    email: "khoa.vu@example.com",
    role: "Viewer",
    status: "Active",
    createdAt: "2026-03-12",
    amount: 450000,
  },
  {
    id: "USR-006",
    name: "Đỗ Hải Yến",
    email: "yen.do@example.com",
    role: "Editor",
    status: "Active",
    createdAt: "2026-03-18",
    amount: 1750000,
  },
  {
    id: "USR-007",
    name: "Hoàng Long Vũ",
    email: "vu.hoang@example.com",
    role: "User",
    status: "Pending",
    createdAt: "2026-03-22",
    amount: 920000,
  },
  {
    id: "USR-008",
    name: "Bùi Thị Mai",
    email: "mai.bui@example.com",
    role: "User",
    status: "Inactive",
    createdAt: "2026-04-01",
    amount: 0,
  },
  {
    id: "USR-009",
    name: "Đặng Tiến Dũng",
    email: "dung.dang@example.com",
    role: "Admin",
    status: "Active",
    createdAt: "2026-04-05",
    amount: 3100000,
  },
  {
    id: "USR-010",
    name: "Trịnh Quốc Bình",
    email: "binh.trinh@example.com",
    role: "Viewer",
    status: "Active",
    createdAt: "2026-04-11",
    amount: 300000,
  },
  {
    id: "USR-011",
    name: "Nông Văn Phương",
    email: "phuong.nong@example.com",
    role: "User",
    status: "Pending",
    createdAt: "2026-04-15",
    amount: 640000,
  },
  {
    id: "USR-012",
    name: "Dương Thu Hương",
    email: "huong.duong@example.com",
    role: "Editor",
    status: "Active",
    createdAt: "2026-04-20",
    amount: 1500000,
  },
  {
    id: "USR-013",
    name: "Lý Văn Nam",
    email: "nam.ly@example.com",
    role: "User",
    status: "Inactive",
    createdAt: "2026-05-02",
    amount: 0,
  },
  {
    id: "USR-014",
    name: "Đào Khánh Linh",
    email: "linh.dao@example.com",
    role: "User",
    status: "Active",
    createdAt: "2026-05-08",
    amount: 2800000,
  },
  {
    id: "USR-015",
    name: "Thái Sơn Tùng",
    email: "tung.thai@example.com",
    role: "Viewer",
    status: "Pending",
    createdAt: "2026-05-14",
    amount: 500000,
  },
  {
    id: "USR-016",
    name: "Phan Nhật Minh",
    email: "minh.phan@example.com",
    role: "Admin",
    status: "Active",
    createdAt: "2026-05-19",
    amount: 4200000,
  },
  {
    id: "USR-017",
    name: "Hồ Bảo Ngân",
    email: "ngan.ho@example.com",
    role: "Editor",
    status: "Active",
    createdAt: "2026-05-25",
    amount: 1100000,
  },
  {
    id: "USR-018",
    name: "Ngô Đức Tuấn",
    email: "tuan.ngo@example.com",
    role: "User",
    status: "Inactive",
    createdAt: "2026-06-01",
    amount: 0,
  },
  {
    id: "USR-019",
    name: "Võ Thanh Hà",
    email: "ha.vo@example.com",
    role: "User",
    status: "Pending",
    createdAt: "2026-06-07",
    amount: 880000,
  },
  {
    id: "USR-020",
    name: "Đinh Hoài Nam",
    email: "nam.dinh@example.com",
    role: "Viewer",
    status: "Active",
    createdAt: "2026-06-12",
    amount: 350000,
  },
  {
    id: "USR-021",
    name: "Nguyễn Khánh Vân",
    email: "van.nguyen@example.com",
    role: "User",
    status: "Active",
    createdAt: "2026-06-18",
    amount: 1950000,
  },
  {
    id: "USR-022",
    name: "Trần Đình Trọng",
    email: "trong.tran@example.com",
    role: "Editor",
    status: "Pending",
    createdAt: "2026-06-25",
    amount: 730000,
  },
  {
    id: "USR-023",
    name: "Lê Thị Hồng",
    email: "hong.le@example.com",
    role: "User",
    status: "Inactive",
    createdAt: "2026-07-02",
    amount: 0,
  },
  {
    id: "USR-024",
    name: "Phạm Quốc Huy",
    email: "huy.pham@example.com",
    role: "Admin",
    status: "Active",
    createdAt: "2026-07-10",
    amount: 3800000,
  },
  {
    id: "USR-025",
    name: "Cao Thanh Sơn",
    email: "son.cao@example.com",
    role: "Viewer",
    status: "Active",
    createdAt: "2026-07-15",
    amount: 600000,
  },
] as const satisfies readonly TableRow[];
export const statusStyles = {
  Active: "bg-emerald-50 text-emerald-700 ring-emerald-600/20",
  Pending: "bg-amber-50 text-amber-700 ring-amber-600/20",
  Inactive: "bg-zinc-100 text-zinc-600 ring-zinc-500/10",
} as const;
