import {
  PERSONAL_COURSES_DETAIL_BUILDER_KEY,
  PERSONAL_COURSES_DETAIL_BUILDER_TITLE,
  PERSONAL_COURSES_DETAIL_URL_BUILDER,
} from "./constants";

export const personalCoursesDetailBuilderRouteConfig = {
  key: {
    PERSONAL_COURSE_DETAIL: PERSONAL_COURSES_DETAIL_BUILDER_KEY,
  },

  title: {
    [PERSONAL_COURSES_DETAIL_BUILDER_KEY]:
      PERSONAL_COURSES_DETAIL_BUILDER_TITLE,
  },
  urlBuilder: {
    [PERSONAL_COURSES_DETAIL_BUILDER_KEY]: PERSONAL_COURSES_DETAIL_URL_BUILDER,
  },
};
